#!/usr/bin/env python3
"""Check a report TeX file for procedure coverage and disallowed content."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from common import read_json, write_json


STEP_ID_RE = re.compile(r"\bP\d{2}\b")
PRINCIPLE_LABEL_RE = re.compile(r"\\label\{(fig:principle-[^}]+)\}")
ABSTRACT_RE = re.compile(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", re.IGNORECASE | re.DOTALL)
TABLE_BLOCK_RE = re.compile(r"\\begin\{(?P<env>table\*?|longtable)\}(?P<body>.*?)\\end\{(?P=env)\}", re.DOTALL)
TABULAR_RE = re.compile(r"\\begin\{tabular\}(?:\[[^\]]*\])?\{(?P<spec>[^}]*)\}", re.DOTALL)
TABULARX_RE = re.compile(r"\\begin\{tabularx\}\{(?P<width>[^}]*)\}\{(?P<spec>[^}]*)\}", re.DOTALL)
CAPTION_RE = re.compile(r"\\caption(?:\[[^\]]*\])?\{(?P<caption>[^}]*)\}", re.DOTALL)
DISCUSSION_SECTION_RE = re.compile(
    r"\\section\*?\{(?P<title>[^}]*(?:discussion|讨论)[^}]*)\}(?P<body>.*?)(?=\\section\*?\{|\\appendix\b|\Z)",
    re.IGNORECASE | re.DOTALL,
)
FURTHER_DISCUSSION_SECTION_RE = re.compile(
    r"\\section\*?\{(?P<title>[^}]*(?:further discussion|进一步讨论|延伸讨论)[^}]*)\}(?P<body>.*?)(?=\\section\*?\{|\\appendix\b|\Z)",
    re.IGNORECASE | re.DOTALL,
)
DEFAULT_FORBIDDEN = [
    r"senior report",
    r"reference report",
    r"参考报告",
    r"学长",
    r"师兄",
]
DEFAULT_IRRELEVANT = [
    r"workflow test",
    r"test draft",
    r"reference-data test draft",
    r"copied senior report",
    r"auto[- ]generated",
    r"generated automatically",
    r"generated by ai",
    r"generated with ai",
    r"\bcodex\b",
    r"\bchatgpt\b",
    r"\bopenai\b",
    r"\bmineru\b",
    r"decoded json",
    r"decoded handout",
    r"extracted from the handout",
    r"transcribed from the note",
    r"user confirmation required",
    r"sidebar",
    r"items needed to replace the draft placeholders",
    r"suggested raw-data tables",
    r"open tbd requests",
    r"draft analysis prompts",
    r"official handout",
    r"experimental workflow",
    r"recorded notebook pages?",
    r"transferred data",
    r"marked for confirmation",
    r"final quantitative analysis is frozen",
    r"report is written in english",
    r"follows the official handout structure",
]
ABSTRACT_META_PATTERNS = [
    r"official handout",
    r"workflow",
    r"notebook pages?",
    r"transferred data",
    r"marked for confirmation",
    r"placeholder",
    r"\bTBD\b",
    r"needs input",
    r"report is written in",
    r"follows the .* structure",
]
STAR_SPEC_RE = re.compile(r"\*\{(\d+)\}\{([^{}]+)\}")
DISCUSSION_RELIABILITY_PATTERNS = [
    r"\breliable\b",
    r"\bunreliable\b",
    r"\bpartially reliable\b",
    r"\bcredible\b",
    r"\bnot reliable\b",
    r"可靠",
    r"不可靠",
    r"部分可靠",
    r"可信",
]
DISCUSSION_ERROR_PATTERNS = [
    r"error source",
    r"systematic",
    r"random error",
    r"uncertaint",
    r"deviation",
    r"resolution",
    r"misalign",
    r"误差",
    r"偏差",
    r"不确定度",
    r"误差来源",
]
DISCUSSION_IMPROVEMENT_PATTERNS = [
    r"improv",
    r"optimiz",
    r"reduce error",
    r"future work",
    r"改进",
    r"优化",
    r"减少误差",
    r"进一步",
]
DISCUSSION_COMPARISON_PATTERNS = [
    r"theor",
    r"expected",
    r"literature",
    r"consistent with",
    r"agreement with",
    r"compare",
    r"理论",
    r"文献",
    r"一致",
    r"符合",
    r"对比",
]
DISCUSSION_CITATION_PATTERNS = [
    r"\\cite\{",
    r"\[\d+(?:[-,]\d+)*\]",
]
COMMAND_LIKE_RE = re.compile(r"^\s*(?:%|\\)")
EVIDENCE_MARKER_RE = re.compile(r"%\s*evidence:(?P<group>[A-Za-z0-9._-]+)")
STRONG_CERTAINTY_PATTERNS = [
    r"\bclearly proves\b",
    r"\bproves\b",
    r"\bconfirms\b",
    r"\bdemonstrates\b",
    r"\bdefinitive(?:ly)?\b",
    r"明确证明",
    r"清楚表明",
    r"证实",
]


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def detect_two_column(text: str) -> bool:
    lowered = text.lower()
    return "twocolumn" in lowered or r"\twocolumn" in text


def count_columns(spec: str) -> int:
    total = 0
    remaining = spec
    while True:
        match = STAR_SPEC_RE.search(remaining)
        if not match:
            break
        total += int(match.group(1)) * count_columns(match.group(2))
        remaining = remaining[: match.start()] + remaining[match.end() :]
    cleaned = re.sub(r"@\{[^}]*\}|!\{[^}]*\}|>\{[^}]*\}|<\{[^}]*\}|\s|\|", "", remaining)
    total += sum(1 for char in cleaned if char in "lcrXSpmb")
    return total


def summarize_table_context(index: int, block: str) -> str:
    match = CAPTION_RE.search(block)
    if match:
        caption = normalize(match.group("caption"))
        if caption:
            return f"table {index} ({caption[:60]})"
    return f"table {index}"


def parse_procedures(path: Path) -> list[dict[str, str]]:
    steps: list[dict[str, str]] = []
    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("<!--"):
            continue
        id_match = STEP_ID_RE.search(line)
        if id_match:
            step_id = id_match.group(0)
            text = line.replace(step_id, "").replace("[]", "").replace("[", "").replace("]", "").strip(":- \t")
            steps.append({"id": step_id, "text": text})
            continue
        stripped = re.sub(r"^\s*(?:[-*]|\d+[.)])\s*", "", line)
        if stripped:
            step_id = f"P{len(steps) + 1:02d}"
            steps.append({"id": step_id, "text": stripped})
    return steps


def coverage_report(tex_text: str, procedures: list[dict[str, str]]) -> list[dict[str, object]]:
    normalized_tex = normalize(tex_text)
    lines = [normalize(line) for line in tex_text.splitlines() if line.strip()]
    payload: list[dict[str, object]] = []
    for step in procedures:
        marker = step["id"].lower()
        marker_present = marker.lower() in normalized_tex or f"procedure:{marker.lower()}" in normalized_tex
        fuzzy_match = False
        if not marker_present and step["text"]:
            candidate = normalize(step["text"])
            if candidate and len(candidate) >= 8:
                fuzzy_match = any(candidate in line for line in lines)
        matched = marker_present or fuzzy_match
        payload.append(
            {
                "id": step["id"],
                "text": step["text"],
                "matched": matched,
                "match_mode": "marker" if marker_present else ("text" if fuzzy_match else "missing"),
            }
        )
    return payload


def find_patterns(text: str, patterns: list[str]) -> list[str]:
    hits: list[str] = []
    for pattern in patterns:
        if re.search(pattern, text, flags=re.IGNORECASE):
            hits.append(pattern)
    return hits


def collect_unstyled_placeholder_lines(text: str) -> list[str]:
    hits: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        lowered = line.lower()
        if "tbd" not in lowered and "to be done" not in lowered and "needs input" not in lowered:
            continue
        if "\\NeedsInput{" in line or "\\textcolor{" in line:
            continue
        hits.append(line)
    return hits


def find_unreferenced_principle_labels(text: str) -> list[str]:
    hits: list[str] = []
    labels = PRINCIPLE_LABEL_RE.findall(text)
    for label in labels:
        escaped = re.escape(label)
        ref_patterns = [
            rf"\\ref\{{{escaped}\}}",
            rf"\\autoref\{{{escaped}\}}",
            rf"\\cref\{{{escaped}\}}",
            rf"\\Cref\{{{escaped}\}}",
            rf"\\figref\{{{escaped}\}}",
        ]
        if not any(re.search(pattern, text) for pattern in ref_patterns):
            hits.append(label)
    return hits


def catalogue_checks(text: str) -> dict[str, bool]:
    toc_index = text.find(r"\tableofcontents")
    first_section_match = re.search(r"\\section\*?\{", text)
    keyword_match = re.search(r"\\keywords?\b|\\begin\{keywords\}", text)
    has_catalogue = toc_index != -1
    has_hyperlinks = (
        r"\usepackage{hyperref}" in text
        or r"\usepackage[hidelinks]{hyperref}" in text
        or r"\hypersetup{" in text
        or r"\hyperref[" in text
        or r"\href{" in text
    )
    position_ok = False
    if has_catalogue and first_section_match:
        position_ok = toc_index < first_section_match.start()
        if keyword_match:
            position_ok = position_ok and toc_index > keyword_match.start()
    return {
        "has_catalogue": has_catalogue,
        "has_hyperlinks": has_hyperlinks,
        "catalogue_position_ok": position_ok,
    }


def abstract_checks(text: str) -> dict[str, object]:
    match = ABSTRACT_RE.search(text)
    if not match:
        return {
            "has_abstract": False,
            "abstract_meta_hits": [],
        }
    abstract_text = match.group(1)
    return {
        "has_abstract": True,
        "abstract_meta_hits": find_patterns(abstract_text, ABSTRACT_META_PATTERNS),
    }


def scaffold_thinking_questions(body_scaffold: dict[str, object] | None) -> list[str]:
    if not isinstance(body_scaffold, dict):
        return []

    questions: list[str] = []
    for section in body_scaffold.get("scaffold_sections", []) or []:
        if not isinstance(section, dict):
            continue
        for item in section.get("thinking_questions", []) or []:
            text = str(item).strip()
            if text:
                questions.append(text)
    return questions


def discussion_checks(text: str, body_scaffold: dict[str, object] | None = None) -> dict[str, object]:
    match = DISCUSSION_SECTION_RE.search(text)
    if not match:
        return {
            "has_discussion_section": False,
            "discussion_issues": ["No discussion section was found."],
        }

    discussion_text = match.group("body")
    issues: list[str] = []
    scaffold_questions = scaffold_thinking_questions(body_scaffold)
    if not find_patterns(discussion_text, DISCUSSION_RELIABILITY_PATTERNS):
        issues.append("The discussion does not make an explicit reliability judgment.")
    if not find_patterns(discussion_text, DISCUSSION_COMPARISON_PATTERNS):
        issues.append("The discussion does not clearly compare the result with theory or literature expectations.")
    if not find_patterns(discussion_text, DISCUSSION_ERROR_PATTERNS):
        issues.append("The discussion does not identify concrete error sources or limitations.")
    if not find_patterns(discussion_text, DISCUSSION_IMPROVEMENT_PATTERNS):
        issues.append("The discussion does not include improvement suggestions or further physical interpretation.")
    if not find_patterns(discussion_text, DISCUSSION_CITATION_PATTERNS):
        issues.append("The discussion does not show literature support or citations.")
    if scaffold_questions and "assigned thinking questions" not in normalize(discussion_text):
        issues.append("Body scaffold requires an `Assigned Thinking Questions` subsection, but the compiled draft does not contain one.")
    return {
        "has_discussion_section": True,
        "discussion_issues": issues,
    }


def evidence_placement_checks(text: str, evidence_plan: dict[str, object] | None = None) -> dict[str, object]:
    marker_counts: dict[str, int] = {}
    for match in EVIDENCE_MARKER_RE.finditer(text):
        group_id = match.group("group")
        marker_counts[group_id] = marker_counts.get(group_id, 0) + 1

    issues: list[str] = []
    units = []
    if isinstance(evidence_plan, dict):
        units = [item for item in evidence_plan.get("evidence_units", []) if isinstance(item, dict)]

    for unit in units:
        group_id = str(unit.get("group_id") or "")
        if not group_id:
            continue
        count = marker_counts.get(group_id, 0)
        if count == 0:
            issues.append(f"Planned evidence group `{group_id}` never appears in TeX evidence markers.")
        elif count < 2:
            issues.append(f"Evidence group `{group_id}` has no nearby figure block marker after its analysis marker.")

    return {
        "evidence_marker_counts": marker_counts,
        "evidence_placement_issues": issues,
    }


def further_discussion_checks(
    text: str,
    evidence_plan: dict[str, object] | None = None,
    discussion_candidates: dict[str, object] | None = None,
) -> dict[str, object]:
    match = FURTHER_DISCUSSION_SECTION_RE.search(text)
    body = match.group("body") if match else ""
    has_section = bool(match)
    issues: list[str] = []

    candidate_list: list[dict[str, object]] = []
    if isinstance(discussion_candidates, dict):
        raw_items = discussion_candidates.get("discussion_ideas") or discussion_candidates.get("discussion_candidates") or []
        candidate_list = [item for item in raw_items if isinstance(item, dict)]

    if has_section and body.strip() and not candidate_list:
        issues.append("The Further Discussion section contains claims but no discussion candidates back it.")

    low_confidence_candidates = [item for item in candidate_list if str(item.get("confidence_level") or "") == "low"]
    if has_section and low_confidence_candidates and find_patterns(body, STRONG_CERTAINTY_PATTERNS):
        issues.append("The Further Discussion wording is too strong for low-confidence candidates.")

    signaled_group_ids: set[str] = set()
    if isinstance(evidence_plan, dict):
        for unit in evidence_plan.get("evidence_units", []):
            if not isinstance(unit, dict):
                continue
            group_id = str(unit.get("group_id") or "")
            if not group_id:
                continue
            warnings = unit.get("warnings") or []
            anomaly_signals = unit.get("anomaly_signals") or []
            mapping_confidence = str(unit.get("mapping_confidence") or "")
            if warnings or anomaly_signals or mapping_confidence == "low":
                signaled_group_ids.add(group_id)

    candidate_group_ids: set[str] = set()
    for item in candidate_list:
        candidate_group_ids.update(str(group_id) for group_id in item.get("source_group_ids", []) if group_id)

    for group_id in sorted(signaled_group_ids - candidate_group_ids):
        issues.append(f"Evidence group `{group_id}` has an anomaly or ambiguity signal but no discussion candidate was generated.")

    if candidate_list and not has_section:
        issues.append("Discussion candidates exist, but no Further Discussion section was found.")

    return {
        "has_further_discussion_section": has_section,
        "further_discussion_issues": issues,
    }


def compact_spacing_checks(text: str) -> dict[str, object]:
    lines = text.splitlines()
    issues: list[str] = []
    issue_limit = 12
    index = 0

    def is_command_like(raw_line: str) -> bool:
        return bool(COMMAND_LIKE_RE.match(raw_line.strip()))

    while index < len(lines):
        if lines[index].strip():
            index += 1
            continue

        start = index
        while index < len(lines) and not lines[index].strip():
            index += 1
        end = index - 1
        blank_count = end - start + 1

        prev_index = start - 1
        while prev_index >= 0 and not lines[prev_index].strip():
            prev_index -= 1
        next_index = index
        while next_index < len(lines) and not lines[next_index].strip():
            next_index += 1

        prev_line = lines[prev_index].strip() if prev_index >= 0 else ""
        next_line = lines[next_index].strip() if next_index < len(lines) else ""

        if blank_count > 1 and len(issues) < issue_limit:
            issues.append(f"Multiple consecutive blank lines appear near source lines {start + 1}-{end + 1}.")

        if prev_line and next_line and is_command_like(prev_line) and is_command_like(next_line) and len(issues) < issue_limit:
            issues.append(
                f"Redundant blank line between `{prev_line[:40]}` and `{next_line[:40]}` near source lines {prev_index + 1}-{next_index + 1}."
            )

        if len(issues) >= issue_limit:
            break

    return {
        "spacing_issues": issues,
    }


def table_layout_checks(text: str) -> dict[str, object]:
    if not detect_two_column(text):
        return {
            "is_two_column": False,
            "table_layout_issues": [],
        }

    issues: list[str] = []
    for index, match in enumerate(TABLE_BLOCK_RE.finditer(text), start=1):
        env = match.group("env")
        body = match.group("body")
        block = match.group(0)
        context = summarize_table_context(index, block)
        lowered_block = block.lower()

        if env == "longtable":
            issues.append(f"{context}: avoid longtable in the two-column template.")
            continue

        if env == "table*" and "% qc:allow-table-star" not in lowered_block:
            issues.append(
                f"{context}: table* in two-column mode needs deliberate review; prefer a column-width table or split continuation tables unless both-column width is truly necessary."
            )

        if r"\resizebox{\textwidth}" in body or r"\begin{tabularx}{\textwidth}" in body:
            issues.append(f"{context}: uses \\textwidth inside a two-column table block and is likely to overflow the column layout.")

        row_count = len(re.findall(r"(?<!\\)\\\\", body))
        if row_count >= 18 and "% qc:allow-tall-table" not in lowered_block:
            issues.append(
                f"{context}: approximately {row_count} body rows appear in one table; split it into shorter continuation tables for readability."
            )

        specs: list[tuple[str, str, str | None]] = []
        specs.extend(("tabular", item.group("spec"), None) for item in TABULAR_RE.finditer(body))
        specs.extend(("tabularx", item.group("spec"), item.group("width")) for item in TABULARX_RE.finditer(body))
        for kind, spec, width in specs:
            column_count = count_columns(spec)
            wrapped_columns = any(token in spec for token in ("X", "p{", "m{", "b{"))
            compact_layout = any(token in body for token in (r"\small", r"\scriptsize", r"\footnotesize"))
            resized_to_column = any(
                token in body for token in (r"\resizebox{\columnwidth}", r"\resizebox{\linewidth}", r"\begin{adjustbox}", r"max width=\columnwidth", r"max width=\linewidth")
            )
            if kind == "tabularx" and width and width.strip() == r"\textwidth":
                issues.append(f"{context}: tabularx is set to \\textwidth inside a two-column report; use \\columnwidth or split the table.")
            if column_count >= 7 and not (wrapped_columns or compact_layout or resized_to_column or env == "table*"):
                issues.append(
                    f"{context}: roughly {column_count} columns are laid out without wrapped columns or a column-width fitting strategy; shorten headers, wrap cells, or split the table."
                )

    return {
        "is_two_column": True,
        "table_layout_issues": issues,
    }


def markdown_report(summary: dict[str, object]) -> str:
    lines = [
        "# Report QC Summary",
        "",
        f"- Pass: `{summary['pass']}`",
        f"- Procedure coverage: {summary['covered_steps']} / {summary['total_steps']}",
        f"- TBD placeholders: {summary['tbd_count']}",
        "",
    ]
    if summary["missing_steps"]:
        lines.extend(["## Missing Steps", ""])
        for item in summary["missing_steps"]:
            lines.append(f"- {item['id']}: {item['text']}")
        lines.append("")
    if summary["forbidden_hits"]:
        lines.extend(["## Forbidden Phrases", ""])
        for hit in summary["forbidden_hits"]:
            lines.append(f"- `{hit}`")
        lines.append("")
    if summary["irrelevant_hits"]:
        lines.extend(["## Irrelevant Leftovers", ""])
        for hit in summary["irrelevant_hits"]:
            lines.append(f"- `{hit}`")
        lines.append("")
    if summary["placeholder_lines"]:
        lines.extend(["## Placeholder Lines", ""])
        for line in summary["placeholder_lines"]:
            lines.append(f"- {line}")
        lines.append("")
    if summary["unstyled_placeholder_lines"]:
        lines.extend(["## Unstyled Placeholder Lines", ""])
        for line in summary["unstyled_placeholder_lines"]:
            lines.append(f"- {line}")
        lines.append("")
    if summary["unreferenced_principle_labels"]:
        lines.extend(["## Unreferenced Principle Figures", ""])
        for label in summary["unreferenced_principle_labels"]:
            lines.append(f"- `{label}`")
        lines.append("")
    if summary["abstract_meta_hits"]:
        lines.extend(["## Abstract Meta Language", ""])
        for hit in summary["abstract_meta_hits"]:
            lines.append(f"- `{hit}`")
        lines.append("")
    if not summary["has_catalogue"] or not summary["catalogue_position_ok"] or not summary["has_hyperlinks"]:
        lines.extend(["## Catalogue Checks", ""])
        lines.append(f"- Has catalogue: `{summary['has_catalogue']}`")
        lines.append(f"- Catalogue position ok: `{summary['catalogue_position_ok']}`")
        lines.append(f"- Hyperlinks enabled: `{summary['has_hyperlinks']}`")
        lines.append("")
    if summary["table_layout_issues"]:
        lines.extend(["## Table Layout Issues", ""])
        for issue in summary["table_layout_issues"]:
            lines.append(f"- {issue}")
        lines.append("")
    if summary["discussion_issues"]:
        lines.extend(["## Discussion Issues", ""])
        for issue in summary["discussion_issues"]:
            lines.append(f"- {issue}")
        lines.append("")
    if summary["evidence_placement_issues"]:
        lines.extend(["## Evidence Placement Warnings", ""])
        for issue in summary["evidence_placement_issues"]:
            lines.append(f"- {issue}")
        lines.append("")
    if summary["further_discussion_issues"]:
        lines.extend(["## Further Discussion Warnings", ""])
        for issue in summary["further_discussion_issues"]:
            lines.append(f"- {issue}")
        lines.append("")
    if summary["spacing_issues"]:
        lines.extend(["## Compact Spacing Issues", ""])
        for issue in summary["spacing_issues"]:
            lines.append(f"- {issue}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tex", required=True)
    parser.add_argument("--procedures", required=True)
    parser.add_argument("--forbidden", action="append", default=[])
    parser.add_argument("--irrelevant", action="append", default=[])
    parser.add_argument("--output-markdown", required=True)
    parser.add_argument("--output-json")
    parser.add_argument("--evidence-plan")
    parser.add_argument("--discussion-candidates")
    parser.add_argument("--body-scaffold")
    args = parser.parse_args()

    tex_path = Path(args.tex)
    procedures_path = Path(args.procedures)
    tex_text = tex_path.read_text(encoding="utf-8", errors="replace")
    procedures = parse_procedures(procedures_path)
    coverage = coverage_report(tex_text, procedures)
    missing_steps = [item for item in coverage if not item["matched"]]
    forbidden_hits = find_patterns(tex_text, DEFAULT_FORBIDDEN + args.forbidden)
    irrelevant_hits = find_patterns(tex_text, DEFAULT_IRRELEVANT + args.irrelevant)
    placeholder_lines = [line.strip() for line in tex_text.splitlines() if "TBD" in line or "TODO" in line]
    unstyled_placeholder_lines = collect_unstyled_placeholder_lines(tex_text)
    unreferenced_principle_labels = find_unreferenced_principle_labels(tex_text)
    abstract_summary = abstract_checks(tex_text)
    catalogue_summary = catalogue_checks(tex_text)
    body_scaffold = read_json(Path(args.body_scaffold)) if args.body_scaffold else None
    discussion_summary = discussion_checks(tex_text, body_scaffold if isinstance(body_scaffold, dict) else None)
    evidence_plan = read_json(Path(args.evidence_plan)) if args.evidence_plan else None
    discussion_candidates = read_json(Path(args.discussion_candidates)) if args.discussion_candidates else None
    evidence_summary = evidence_placement_checks(tex_text, evidence_plan if isinstance(evidence_plan, dict) else None)
    further_discussion_summary = further_discussion_checks(
        tex_text,
        evidence_plan if isinstance(evidence_plan, dict) else None,
        discussion_candidates if isinstance(discussion_candidates, dict) else None,
    )
    spacing_summary = compact_spacing_checks(tex_text)
    table_summary = table_layout_checks(tex_text)

    summary = {
        "tex": str(tex_path),
        "procedures": str(procedures_path),
        "total_steps": len(procedures),
        "covered_steps": len(procedures) - len(missing_steps),
        "missing_steps": missing_steps,
        "forbidden_hits": forbidden_hits,
        "irrelevant_hits": irrelevant_hits,
        "tbd_count": tex_text.count("TBD"),
        "placeholder_lines": placeholder_lines,
        "unstyled_placeholder_lines": unstyled_placeholder_lines,
        "unreferenced_principle_labels": unreferenced_principle_labels,
        **abstract_summary,
        **catalogue_summary,
        **discussion_summary,
        **evidence_summary,
        **further_discussion_summary,
        **spacing_summary,
        **table_summary,
        "pass": not missing_steps and not forbidden_hits and not irrelevant_hits and not unstyled_placeholder_lines and not unreferenced_principle_labels and not abstract_summary["abstract_meta_hits"] and catalogue_summary["has_catalogue"] and catalogue_summary["catalogue_position_ok"] and catalogue_summary["has_hyperlinks"] and not discussion_summary["discussion_issues"] and not spacing_summary["spacing_issues"] and not table_summary["table_layout_issues"],
    }

    Path(args.output_markdown).write_text(markdown_report(summary), encoding="utf-8")
    if args.output_json:
        write_json(Path(args.output_json), summary)

    print(json.dumps({"pass": summary["pass"], "output_markdown": args.output_markdown}, ensure_ascii=False))
    return 0 if summary["pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
