from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


HEADING_RE = re.compile(r"(?m)^\\(section|subsection)\{([^}]+)\}[ \t]*\n?")
PLACEHOLDER_TOKENS = ("\\NeedsInput{", "PLACEHOLDER", "TBD", "TODO")
OWNED_MARKER_PREFIX = "% course-lab-final-staging:"
ALLOW_OVERWRITE_MARKER = "% course-lab-final-staging:allow-overwrite"
MAX_DRAFT_SCAFFOLD_CHARS = 280
DRAFT_CUE_PATTERNS = (
    "draft",
    "placeholder",
    "guide",
    "skeleton",
    "temporary",
    "provisional",
    "to be expanded",
    "to be completed",
    "to be filled",
    "will be written later",
    "for later staging",
    "generated by previous skill",
)
AUTHOR_CONTENT_BLOCKERS = (
    r"\begin{equation",
    r"\begin{table",
    r"\begin{tabular",
    r"\begin{figure",
    r"\begin{align",
    r"\includegraphics",
    r"\cite",
    r"\ref",
)
BUCKET_SYNONYMS = {
    "process": (
        "Experimental Procedure",
        "Experimental Procedure and Observations",
        "Experimental Process and Observations",
        "Procedure",
        "Methods",
        "Methods and Observations",
        "Experimental Content",
    ),
    "results": (
        "Results and Analysis",
        "Experimental Results",
        "Data and Analysis",
        "Data Analysis",
        "Analysis",
        "Analysis and Results",
    ),
    "discussion": (
        "Local Discussion",
        "Discussion and Analysis",
    ),
    "appendix": (
        "Code",
        "Appendix Code",
    ),
}


def strip_placeholder_content(body: str) -> str:
    cleaned_lines: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line
        if OWNED_MARKER_PREFIX in line or ALLOW_OVERWRITE_MARKER in line:
            continue
        if "\\NeedsInput{" in line:
            line = re.sub(r"\\NeedsInput\{[^{}]*\}", "", line)
        if any(token in line for token in ("PLACEHOLDER", "TBD", "TODO")):
            continue
        cleaned_lines.append(line)
    return "\n".join(cleaned_lines).strip()


def ensure_parent_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def maybe_read_json(path: Path | None) -> Any:
    if path is None or not path.exists():
        return None
    return read_json(path)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def read_text_if_exists(path: Path | None) -> str:
    if path is None or not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def write_json(path: Path, payload: Any) -> None:
    ensure_parent_dir(path)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    ensure_parent_dir(path)
    path.write_text(text, encoding="utf-8")


def normalize_heading(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip()).casefold()


def safe_label(text: str, *, default: str = "item") -> str:
    lowered = text.strip().lower()
    cleaned = re.sub(r"[^a-z0-9]+", "-", lowered)
    cleaned = re.sub(r"-{2,}", "-", cleaned).strip("-")
    return cleaned or default


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    output = text
    for source, target in replacements.items():
        output = output.replace(source, target)
    return output


def heading_ranges(tex: str) -> list[dict[str, object]]:
    matches = list(HEADING_RE.finditer(tex))
    headings: list[dict[str, object]] = []
    last_section_heading = ""
    last_section_normalized = ""

    for match in matches:
        command = match.group(1)
        heading = match.group(2).strip()
        level = 1 if command == "section" else 2
        normalized_heading = normalize_heading(heading)
        if level == 1:
            last_section_heading = heading
            last_section_normalized = normalized_heading

        headings.append(
            {
                "command": command,
                "level": level,
                "heading": heading,
                "normalized_heading": normalized_heading,
                "start": match.start(),
                "body_start": match.end(),
                "line": tex.count("\n", 0, match.start()) + 1,
                "parent_section_heading": last_section_heading if level > 1 else "",
                "parent_section_normalized": last_section_normalized if level > 1 else "",
            }
        )

    for index, heading in enumerate(headings):
        level = int(heading["level"])
        end = len(tex)
        for candidate in headings[index + 1 :]:
            if int(candidate["level"]) <= level:
                end = int(candidate["start"])
                break
        heading["end"] = end

    return headings


def safe_to_overwrite(body: str) -> bool:
    stripped = body.strip()
    if not stripped:
        return True
    if ALLOW_OVERWRITE_MARKER in stripped:
        return True
    if OWNED_MARKER_PREFIX in stripped:
        return True
    if any(token in stripped for token in PLACEHOLDER_TOKENS):
        remaining = strip_placeholder_content(stripped)
        if not remaining:
            return True
        return looks_like_draft_scaffold(remaining)
    return looks_like_draft_scaffold(stripped)


def looks_like_draft_scaffold(body: str) -> bool:
    stripped = body.strip()
    if not stripped:
        return False
    if len(stripped) > MAX_DRAFT_SCAFFOLD_CHARS:
        return False
    if re.search(r"\n\s*\n", stripped):
        return False
    if any(blocker in stripped for blocker in AUTHOR_CONTENT_BLOCKERS):
        return False

    normalized = re.sub(r"\s+", " ", stripped).casefold()
    return any(cue in normalized for cue in DRAFT_CUE_PATTERNS)


def wrap_owned_region(slug: str, body: str) -> str:
    cleaned = body.strip()
    lines = [f"{OWNED_MARKER_PREFIX}{slug}:begin"]
    if cleaned:
        lines.append(cleaned)
    lines.append(f"{OWNED_MARKER_PREFIX}{slug}:end")
    return "\n".join(lines).rstrip() + "\n"


def scaffold_block_order(body_scaffold: dict[str, object] | None) -> list[str]:
    if not isinstance(body_scaffold, dict):
        return []

    order: list[str] = []
    for section in body_scaffold.get("scaffold_sections", []):
        if not isinstance(section, dict):
            continue
        heading = str(section.get("heading") or "").strip()
        normalized = normalize_heading(heading)
        if not normalized:
            continue
        order.append(normalized)
    return order


def _format_candidates(candidates: list[dict[str, object]]) -> str:
    return "; ".join(
        f"{item['command']}{{{item['heading']}}} at line {item['line']}"
        for item in candidates
    )


def _filter_by_preferred_block(
    candidates: list[dict[str, object]],
    preferred_block: str | None,
) -> list[dict[str, object]]:
    if not preferred_block:
        return candidates
    filtered = [
        item
        for item in candidates
        if str(item.get("parent_section_normalized") or "") == preferred_block
    ]
    return filtered or candidates


def _candidates_in_preferred_block(
    candidates: list[dict[str, object]],
    preferred_block: str | None,
) -> list[dict[str, object]]:
    if not preferred_block:
        return []
    return [
        item
        for item in candidates
        if str(item.get("parent_section_normalized") or "") == preferred_block
    ]


def _select_synonym_candidate(
    candidates: list[dict[str, object]],
    *,
    preferred_block: str | None,
    block_order: list[str],
    bucket_name: str,
) -> dict[str, object]:
    preferred_matches = _filter_by_preferred_block(candidates, preferred_block)
    if len(preferred_matches) == 1:
        return preferred_matches[0]
    if preferred_block and len(preferred_matches) > 1:
        raise SystemExit(
            f"Ambiguous {bucket_name} heading in preferred experiment block {preferred_block}: "
            f"{_format_candidates(preferred_matches)}"
        )

    for block in block_order:
        block_section_matches = [
            item
            for item in candidates
            if int(item.get("level", 0)) == 1 and str(item.get("normalized_heading") or "") == block
        ]
        if len(block_section_matches) == 1:
            return block_section_matches[0]
        if len(block_section_matches) > 1:
            raise SystemExit(
                f"Ambiguous {bucket_name} top-level heading for experiment block {block}: "
                f"{_format_candidates(block_section_matches)}"
            )

        block_matches = [
            item
            for item in candidates
            if str(item.get("parent_section_normalized") or "") == block
        ]
        if len(block_matches) == 1:
            return block_matches[0]
        if len(block_matches) > 1:
            raise SystemExit(
                f"Ambiguous {bucket_name} heading in experiment block {block}: "
                f"{_format_candidates(block_matches)}"
            )

    grouped: dict[str, list[dict[str, object]]] = {}
    for item in candidates:
        key = str(item.get("parent_section_normalized") or "")
        grouped.setdefault(key, []).append(item)

    if len(grouped) == len(candidates) and len(candidates) > 1:
        return candidates[0]

    raise SystemExit(f"Ambiguous {bucket_name} heading candidates: {_format_candidates(candidates)}")


def resolve_heading_target(
    tex: str,
    *,
    bucket_name: str,
    exact_headings: tuple[str, ...],
    preferred_block: str | None = None,
    block_order: list[str] | None = None,
) -> dict[str, object]:
    headings = heading_ranges(tex)
    exact_norms = {normalize_heading(item) for item in exact_headings}
    synonym_norms = {normalize_heading(item) for item in BUCKET_SYNONYMS.get(bucket_name, ())}

    exact_matches = [item for item in headings if item["normalized_heading"] in exact_norms]
    exact_in_block = _candidates_in_preferred_block(exact_matches, preferred_block)
    if len(exact_in_block) == 1:
        return exact_in_block[0]
    if len(exact_in_block) > 1:
        raise SystemExit(
            f"Ambiguous {bucket_name} heading in preferred experiment block {preferred_block}: "
            f"{_format_candidates(exact_in_block)}"
        )

    synonym_matches = [item for item in headings if item["normalized_heading"] in synonym_norms]
    synonym_in_block = _candidates_in_preferred_block(synonym_matches, preferred_block)
    if len(synonym_in_block) == 1:
        return synonym_in_block[0]
    if len(synonym_in_block) > 1:
        raise SystemExit(
            f"Ambiguous {bucket_name} heading in preferred experiment block {preferred_block}: "
            f"{_format_candidates(synonym_in_block)}"
        )

    if len(exact_matches) == 1:
        return exact_matches[0]
    if len(exact_matches) > 1:
        raise SystemExit(
            f"Ambiguous {bucket_name} heading candidates: {_format_candidates(exact_matches)}"
        )
    if len(synonym_matches) == 1:
        return synonym_matches[0]
    if not synonym_matches:
        joined = ", ".join(exact_headings)
        raise SystemExit(f"Required section not found in main.tex: {joined}")

    return _select_synonym_candidate(
        synonym_matches,
        preferred_block=None,
        block_order=block_order or [],
        bucket_name=bucket_name,
    )


def replace_owned_heading(
    tex: str,
    *,
    bucket_name: str,
    exact_headings: tuple[str, ...],
    slug: str,
    new_body: str,
    preferred_block: str | None = None,
    block_order: list[str] | None = None,
    preserve_if_unsafe: bool = False,
) -> tuple[str, str, str | None, bool]:
    heading = resolve_heading_target(
        tex,
        bucket_name=bucket_name,
        exact_headings=exact_headings,
        preferred_block=preferred_block,
        block_order=block_order,
    )

    start = int(heading["body_start"])
    end = int(heading["end"])
    body = tex[start:end]
    next_preferred_block = str(heading.get("parent_section_normalized") or "") or None
    if not safe_to_overwrite(body):
        if preserve_if_unsafe:
            return tex, str(heading["heading"]), next_preferred_block, False
        raise SystemExit(
            f"Unsafe to overwrite {heading['heading']} section without placeholder or course-lab-final-staging marker"
        )

    replacement = wrap_owned_region(slug, new_body)
    return tex[:start] + replacement + tex[end:], str(heading["heading"]), next_preferred_block, True
