from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parents[1] / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from report_qc import (  # type: ignore
    DEFAULT_IRRELEVANT,
    abstract_checks,
    catalogue_checks,
    collect_unstyled_placeholder_lines,
    compact_spacing_checks,
    coverage_report,
    discussion_checks,
    evidence_placement_checks,
    find_patterns,
    find_unreferenced_principle_labels,
    further_discussion_checks,
    parse_procedures,
    table_layout_checks,
)


FIXTURES = Path(__file__).resolve().parent / "fixtures"


def load_json_fixture(name: str) -> dict[str, object]:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


class ReportQCTests(unittest.TestCase):
    def test_missing_steps_are_detected(self) -> None:
        procedures = parse_procedures(FIXTURES / "sample_procedures.md")
        tex_text = (FIXTURES / "sample_report_bad.tex").read_text(encoding="utf-8")
        coverage = coverage_report(tex_text, procedures)
        matched = {item["id"]: item["matched"] for item in coverage}
        self.assertTrue(matched["P01"])
        self.assertFalse(matched["P02"])

    def test_irrelevant_appendix_patterns_are_detected(self) -> None:
        tex_text = (FIXTURES / "sample_report_bad.tex").read_text(encoding="utf-8")
        hits = find_patterns(tex_text, [r"items needed to replace the draft placeholders"])
        self.assertEqual(hits, [r"items needed to replace the draft placeholders"])

    def test_ai_and_provenance_language_is_detected(self) -> None:
        tex_text = r"""
% Auto-generated by Codex from decoded JSON
\caption{Main apparatus extracted from the handout}
"""
        hits = find_patterns(tex_text, DEFAULT_IRRELEVANT)
        self.assertIn(r"auto[- ]generated", hits)
        self.assertIn(r"\bcodex\b", hits)
        self.assertIn(r"decoded json", hits)
        self.assertIn(r"extracted from the handout", hits)

    def test_unstyled_placeholder_lines_are_detected(self) -> None:
        tex_text = (FIXTURES / "sample_report_bad.tex").read_text(encoding="utf-8")
        hits = collect_unstyled_placeholder_lines(tex_text)
        self.assertTrue(any("TBD:" in line for line in hits))

    def test_unreferenced_principle_labels_are_detected(self) -> None:
        tex_text = r"""
\begin{figure}[H]
\caption{Force curve schematic}
\label{fig:principle-01}
\end{figure}
"""
        self.assertEqual(find_unreferenced_principle_labels(tex_text), ["fig:principle-01"])
        referenced = tex_text + "\nAs shown in Fig.~\\ref{fig:principle-01}, the force curve is used as a schematic diagram.\n"
        self.assertEqual(find_unreferenced_principle_labels(referenced), [])

    def test_catalogue_checks_require_toc_position_and_hyperlinks(self) -> None:
        tex_text = r"""
\usepackage[hidelinks]{hyperref}
\keywords{Crystal optics}
\tableofcontents
\section{Introduction}
\subsection{Background}
"""
        summary = catalogue_checks(tex_text)
        self.assertTrue(summary["has_catalogue"])
        self.assertTrue(summary["catalogue_position_ok"])
        self.assertTrue(summary["has_hyperlinks"])

    def test_abstract_process_language_is_detected(self) -> None:
        tex_text = r"""
\begin{abstract}
The theoretical discussion is built from the official handout and the experimental workflow is matched step by step to the recorded notebook pages. The transferred data remain marked for confirmation.
\end{abstract}
"""
        summary = abstract_checks(tex_text)
        self.assertTrue(summary["has_abstract"])
        self.assertIn(r"official handout", summary["abstract_meta_hits"])
        self.assertIn(r"workflow", summary["abstract_meta_hits"])
        self.assertIn(r"notebook pages?", summary["abstract_meta_hits"])
        self.assertIn(r"transferred data", summary["abstract_meta_hits"])

    def test_table_layout_checks_flag_wide_and_spanning_tables(self) -> None:
        tex_text = r"""
\documentclass[twocolumn]{article}
\begin{table}
\caption{Wide equipment table}
\begin{tabular}{ccccccc}
A&B&C&D&E&F&G\\
1&2&3&4&5&6&7\\
\end{tabular}
\end{table}
\begin{table*}
\caption{Spanning comparison}
\begin{tabular}{cc}
A&B\\
\end{tabular}
\end{table*}
"""
        summary = table_layout_checks(tex_text)
        self.assertTrue(summary["is_two_column"])
        self.assertTrue(any("roughly 7 columns" in issue for issue in summary["table_layout_issues"]))
        self.assertTrue(any("table*" in issue for issue in summary["table_layout_issues"]))

    def test_table_layout_checks_flag_longtable_and_tall_tables(self) -> None:
        rows = "\n".join(f"{index} & value \\\\" for index in range(20))
        tex_text = rf"""
\documentclass[twocolumn]{{article}}
\begin{{longtable}}{{cc}}
A & B\\
\end{{longtable}}
\begin{{table}}
\caption{{Tall measurement table}}
\begin{{tabular}}{{cc}}
{rows}
\end{{tabular}}
\end{{table}}
"""
        summary = table_layout_checks(tex_text)
        self.assertTrue(any("avoid longtable" in issue for issue in summary["table_layout_issues"]))
        self.assertTrue(any("approximately 20 body rows" in issue for issue in summary["table_layout_issues"]))

    def test_discussion_checks_require_reliability_comparison_error_and_citation(self) -> None:
        tex_text = r"""
\section{Experiment Discussion}
The result is partially reliable because the main qualitative trend is consistent with the theoretical expectation and with the teaching-literature discussion.\cite{opticspaper}
The deviation is mainly caused by alignment error, finite instrument resolution, and uncertainty in the sample orientation.
Further improvement would come from repeating the observation and reducing the alignment error.
"""
        summary = discussion_checks(tex_text)
        self.assertTrue(summary["has_discussion_section"])
        self.assertEqual(summary["discussion_issues"], [])

    def test_discussion_checks_flag_generic_short_discussion(self) -> None:
        tex_text = r"""
\section{Experiment Discussion}
The result is good and basically matches the experiment.
"""
        summary = discussion_checks(tex_text)
        self.assertTrue(summary["has_discussion_section"])
        self.assertTrue(any("reliability judgment" in issue for issue in summary["discussion_issues"]))
        self.assertTrue(any("compare the result with theory or literature" in issue for issue in summary["discussion_issues"]))
        self.assertTrue(any("error sources or limitations" in issue for issue in summary["discussion_issues"]))
        self.assertTrue(any("literature support or citations" in issue for issue in summary["discussion_issues"]))

    def test_compact_spacing_checks_flag_command_padding_and_multiple_blank_lines(self) -> None:
        tex_text = r"""
\title{A}

\author{B}


\affil{C}
"""
        summary = compact_spacing_checks(tex_text)
        self.assertTrue(any("Redundant blank line" in issue for issue in summary["spacing_issues"]))
        self.assertTrue(any("Multiple consecutive blank lines" in issue for issue in summary["spacing_issues"]))

    def test_compact_spacing_checks_allow_paragraph_breaks(self) -> None:
        tex_text = r"""
First paragraph line.

Second paragraph line.
"""
        summary = compact_spacing_checks(tex_text)
        self.assertEqual(summary["spacing_issues"], [])

    def test_evidence_placement_checks_flag_missing_nearby_figure_block(self) -> None:
        tex_text = r"""
\section{Results}
% evidence:z-cut-teo2
The z-cut TeO2 result is discussed here in prose, but no local figure marker follows.
"""
        evidence_plan = load_json_fixture("sample_evidence_plan.json")
        summary = evidence_placement_checks(tex_text, evidence_plan)
        self.assertTrue(any("nearby figure block" in issue for issue in summary["evidence_placement_issues"]))
        self.assertTrue(any("mystery-image" in issue for issue in summary["evidence_placement_issues"]))

    def test_further_discussion_checks_flag_claim_without_candidate_backing(self) -> None:
        tex_text = r"""
\section{Further Discussion}
This clearly proves the vague image already gives a definitive explanation.
"""
        summary = further_discussion_checks(tex_text, load_json_fixture("sample_evidence_plan.json"), {"discussion_candidates": []})
        self.assertTrue(any("no discussion candidates back it" in issue for issue in summary["further_discussion_issues"]))

    def test_further_discussion_checks_flag_strong_certainty_for_low_confidence_candidate(self) -> None:
        tex_text = r"""
\section{Further Discussion}
This clearly proves the mystery image shows the true optical behavior.
"""
        discussion_candidates = {"discussion_candidates": [load_json_fixture("sample_discussion_candidates.json")["discussion_candidates"][1]]}
        summary = further_discussion_checks(tex_text, load_json_fixture("sample_evidence_plan.json"), discussion_candidates)
        self.assertTrue(any("too strong for low-confidence" in issue for issue in summary["further_discussion_issues"]))

    def test_further_discussion_checks_flag_missing_candidates_for_anomaly_and_ambiguity_signals(self) -> None:
        tex_text = r"""
\section{Discussion}
The standard discussion ends here.
"""
        summary = further_discussion_checks(tex_text, load_json_fixture("sample_evidence_plan.json"), {"discussion_candidates": []})
        self.assertTrue(any("no discussion candidate" in issue for issue in summary["further_discussion_issues"]))


if __name__ == "__main__":
    unittest.main()
